// The single source of truth for which modules exist and how they're described
// on the dashboard. Adding a module = add an entry here + a component file +
// one line in components/ModuleRoutes.tsx.

import { ModuleMeta } from '../types';

export const MODULES: ModuleMeta[] = [
  {
    id: 'kims-game',
    name: "Kim's Game",
    emoji: '🔍',
    tagline: 'Memorise a tray of objects, then recall what was there.',
    skill: 'Visual attention & working memory',
    category: 'Observation',
    core: true,
    why: "Kim's Game comes from Kipling's novel Kim, where a spy-in-training is drilled on a tray of jewels. It builds the habit of encoding a scene deliberately rather than glancing. Real observation is active: you decide what to notice.",
    book: 'Maria Konnikova — Mastermind: How to Think Like Sherlock Holmes',
  },
  {
    id: 'room-recall',
    name: 'Room Recall',
    emoji: '🪑',
    tagline: 'Study a scene, then answer questions about its details.',
    skill: 'Deliberate observation & recall under questioning',
    category: 'Observation',
    core: true,
    why: 'Eyewitnesses are famously unreliable because attention is selective. Practising recall of a whole scene — counts, colours, positions — trains you to observe broadly and resist filling gaps with assumptions.',
    book: 'Maria Konnikova — Mastermind',
  },
  {
    id: 'memory-palace',
    name: 'Memory Palace',
    emoji: '🏛️',
    tagline: 'Use the method of loci to memorise a deck of cards in order.',
    skill: 'Associative long-term memory (mnemonics)',
    category: 'Memory',
    core: true,
    why: 'Every memory champion uses the method of loci: converting abstract data into vivid images placed along a familiar route. It exploits our strong spatial and visual memory. The PAO (person–action–object) system compresses cards into memorable scenes.',
    book: 'Joshua Foer — Moonwalking with Einstein',
  },
  {
    id: 'calibration-journal',
    name: 'Calibration Journal',
    emoji: '🎯',
    tagline: 'Log predictions with a confidence %, then see if you were right.',
    skill: 'Probabilistic thinking & calibrated confidence',
    category: 'Reasoning',
    core: true,
    why: 'The single most transferable "mentalist" skill is thinking in probabilities and knowing how much to trust your own certainty. Tracking predictions and plotting stated confidence against real hit-rate reveals over- and under-confidence you cannot feel from the inside.',
    book: 'Philip Tetlock — Superforecasting; Daniel Kahneman — Thinking, Fast and Slow',
  },
  {
    id: 'emotion-reader',
    name: 'Emotion Reader',
    emoji: '🎭',
    tagline: 'Identify the emotion behind a scenario, against the clock.',
    skill: 'Reading affect & microexpressions',
    category: 'People-reading',
    core: true,
    why: 'A small set of emotions (happiness, fear, anger, contempt, disgust, sadness, surprise) recur across cultures. Learning their signatures — and, crucially, spotting deviations from a person\'s baseline — is the foundation of people-reading. Track which emotions you miss to find your blind spots.',
    book: 'Paul Ekman — Emotions Revealed',
  },
  {
    id: 'cold-reading',
    name: 'Cold Reading Studio',
    emoji: '🔮',
    tagline: 'Learn the mechanics of Barnum statements — to recognise them.',
    skill: 'Detecting persuasion & vague-language tricks',
    category: 'People-reading',
    core: false,
    why: 'Cold reading works by using statements that feel personal but apply to almost anyone (the Barnum effect), plus high-probability guesses. Understanding the mechanics inoculates you against psychics, con artists, and cult recruiters. This module teaches you to classify the trick, not perform it on people.',
    book: 'Ian Rowland — The Full Facts Book of Cold Reading',
  },
  {
    id: 'abductive-puzzles',
    name: 'Abductive Puzzles',
    emoji: '🧩',
    tagline: 'Generate three explanations before the answer is revealed.',
    skill: 'Abductive reasoning & hypothesis generation',
    category: 'Problem-solving',
    core: false,
    why: 'Abduction is inference to the best explanation. The classic failure is falling in love with your first theory. Forcing yourself to produce three distinct explanations before evaluating any of them keeps the search space open — the habit behind good detectives and diagnosticians.',
    book: 'Maria Konnikova — Mastermind; C. S. Peirce on abduction',
  },
  {
    id: 'deduction-drills',
    name: 'Deduction Drills',
    emoji: '🕵️',
    tagline: 'Pick the best-supported conclusion and name the clue behind it.',
    skill: 'Evidence-based inference vs. guessing',
    category: 'Observation',
    core: false,
    why: 'Holmesian "deduction" is really careful inference: separating what the evidence actually supports from a plausible-sounding leap. Naming exactly which clue backs a conclusion trains you to keep your reasoning traceable instead of intuitive.',
    book: 'Maria Konnikova — Mastermind',
  },
  {
    id: 'number-memory',
    name: 'Number Memory',
    emoji: '🔢',
    tagline: 'Recall a number that grows one digit longer each round.',
    skill: 'Digit span & auditory-verbal working memory',
    category: 'Memory',
    core: false,
    why: 'Digit span is the oldest measure of working memory. Most people top out around 7±2 digits — until they learn to chunk digits into groups and turn them into images. Pushing your span builds the raw buffer that every other memory technique loads from.',
    book: 'Joshua Foer — Moonwalking with Einstein',
  },
  {
    id: 'speed-matrix',
    name: 'Speed Matrix',
    emoji: '🔲',
    tagline: 'Numbers flash on a grid — tap them in order from memory.',
    skill: 'Spatial working memory & rapid encoding',
    category: 'Observation',
    core: false,
    why: 'Inspired by the chimpanzee memory experiments at Kyoto: numbers appear briefly on a grid, then vanish, and you must tap them in ascending order. It trains eidetic-style spatial capture — taking a mental snapshot and reading it back — the same instant-encoding a mentalist uses to scan a room.',
    book: 'Maria Konnikova — Mastermind',
  },
  {
    id: 'fermi-estimation',
    name: 'Fermi Estimation',
    emoji: '📐',
    tagline: 'Give a range you\'re 90% sure contains the true number.',
    skill: 'Quantitative estimation & interval calibration',
    category: 'Reasoning',
    core: false,
    why: 'Enrico Fermi could estimate almost anything by breaking it into knowable pieces. Giving a 90% confidence interval — and seeing how often the truth actually lands inside — trains the same calibration as the prediction journal, but for numbers. Well-calibrated people are right about 90% of the time; most beginners are far too narrow.',
    book: 'Douglas Hubbard — How to Measure Anything; Philip Tetlock — Superforecasting',
  },
  {
    id: 'lie-spotter',
    name: 'Lie Spotter',
    emoji: '🤥',
    tagline: 'Three statements, one is a lie — find it from the language.',
    skill: 'Statement analysis & deception cues',
    category: 'People-reading',
    core: false,
    why: 'Deception often leaks through language, not just faces: fewer self-references, more distancing, over-precision, and unnecessary qualifiers. Learning verbal statement analysis is more reliable than the myth of "body language tells" — and it teaches you to weigh cues rather than trust a gut feeling.',
    book: 'Pamela Meyer — Liespotting',
  },
  {
    id: 'pattern-sequences',
    name: 'Pattern Sequences',
    emoji: '🧮',
    tagline: 'Infer the rule and predict what comes next.',
    skill: 'Inductive reasoning & rule inference',
    category: 'Problem-solving',
    core: false,
    why: 'Induction is spotting the rule behind examples — the engine of pattern recognition. Sequences reward you for finding the simplest rule that fits (and for not over-fitting to noise). It complements abduction: one generates explanations, the other extends patterns.',
    book: 'Douglas Hofstadter — Gödel, Escher, Bach',
  },
];

export function getModule(id: string): ModuleMeta | undefined {
  return MODULES.find((m) => m.id === id);
}

export const CORE_MODULES = MODULES.filter((m) => m.core);
